import 'package:zoobaurumap/models/animal.dart';

const List<Animal> animais = [
  Animal(
    'PAVÃO ALERQUIM',
    'Pavão',
    'assets/animals_images/pavao_alerquim.jpg',
    'O Pavão Alerquim é uma variação rara e exótica do pavão-real, com cores dramáticas! Os machos abrem o leque de penas e vibram as asas para atrair fêmeas.',
    'Pavo Cristatus',
    'Não é um Animal Natural (Raro) (Mutação do Pavão-Azul).',
    '1,2m e 1,6m (Corpo)',
    'sounds/som_pavao_alerquim.mp3',
    'Pav%C3%A3o-azul',
  ),
  Animal(
    'ALPACA',
    'Camelídeos',
    'assets/animals_images/alpaca.jpg',
    'Alpaca, o "ouro dos Andes", a fofa produtora de lã mais luxuosa do mundo! São curiosas e sociáveis (vivem em rebanhos). Cuspidoras seletivas (só cospem em rivais na disputa por comida).',
    'Vicugna Pacos',
    'Não possui status na IUCN.',
    '1,2m e 1,5m (Corpo)',
    'sounds/som_alpaca.mp3',
    'Alpaca',
  ),
  Animal(
    'ONÇA PINTADA',
    'Grandes Felinos',
    'assets/animals_images/onca pintada.jpg',
    'Onça-Pintada, o maior felino das Américas e o rei das florestas tropicais! Excelente nadadora (caça peixes e jacarés dentro da água). Sobe em árvores para arrastar presas pesadas (únicas entre grandes felinos).',
    'Panthera Onca',
    'Quase Ameaçada',
    '1,7m e 2,5m (Cabeça e Corpo)',
    'sounds/som_onca_pintada.mp3',
    'Panthera_onca',
  ),
  Animal(
    'FURÃO',
    'Pequenos Mamíferos',
    'assets/animals_images/furao.jpg',
    'Furão, o carismático e travesso parente doméstico dos mustelídeos! Hiperativos e curiosos, exploram tudo com frenesi ("dança do furão"). Sociáveis com humanos e outros furões (mas podem morder se assustados).',
    'Mustela Putorius Furo',
    'Não possui status na IUCN.',
    '35cm e 50cm (Corpo)',
    'sounds/som_furao.mp3',
    'Fur%C3%A3o',
  ),
  Animal(
    'Cisne-Negro',
    'Aves Marinhas',
    'assets/animals_images/cisne_negro.jpg',
    'Cisne-Negro, a elegância gótica das águas, com plumagem de ébano e bico vermelho-sangue! Batidas de asas sonoras (ouvidas a 2 km de distância!). Voam em formação em V durante migrações.',
    'Cygnus Atratus',
    'Pouco Preocupante',
    '1,1m e 1,4m (Corpo)',
    'sounds/som_cisne_negro.mp3',
    'Cisne-negro',
  ),
  Animal(
    'Urubu-Rei',
    'Aves De Rapina',
    'assets/animals_images/urubu_rei.jpg',
    'Urubu-Rei, o majestoso "monarca das alturas" das florestas tropicais! Domina outros urubus na disputa por carcaças (ganhou o título de "rei"). Planador excepcional: Pode voar horas sem bater as asas, usando correntes de ar quente.',
    'Sarcoramphus Papa',
    'Pouco Preocupante',
    '70cm e 80cm (Corpo)',
    'sounds/som_urubu_rei.mp3',
    'Urubu-rei',
  ),
  Animal(
    'CASUAR',
    'Aves Ratitas',
    'assets/animals_images/casuar.jpg',
    'Casuar, a ave mais perigosa do mundo e um dos últimos dinossauros modernos! Emite rugidos de baixa frequência (inaudíveis para humanos, mas sentidos como vibrações). Ataca com chutes frontais (capazes de ferir humanos gravemente).',
    'Casuarius Casuarius',
    'Vulnerável',
    '1,5m e 1,8m (Corpo)',
    'sounds/som_casuar.mp3',
    'Casuar-do-sul',
  ),
  Animal(
    'Guará',
    'Aves Ribeirinhas',
    'assets/animals_images/guara.jpg',
    'Guará, o "flamingo brasileiro" que pinta os manguezais de vermelho! Vive em bandos de dezenas a centenas de indivíduos. Pais cuidam juntos dos filhotes por 6 semanas.',
    'Eudocimus Ruber',
    'Pouco Preocupante',
    '55cm e 65cm (Altura)',
    'sounds/som_guara.mp3',
    'Guará',
  ),
  Animal(
    'GUARIBA',
    'Grandes Primatas Brasileiros',
    'assets/animals_images/Guariba.jpg',
    'O Guariba, também conhecido como Bugio ou Macaco-Uivador, são famosos por seus uivos potentes que podem ser ouvidos a quilômetros de distância, graças a um osso hioide ampliado que atua como uma caixa de ressonância.',
    'Atelidae Alouatta',
    'Vulnerável',
    '50cm e 1m (Corpo)',
    'sounds/som_guariba.mp3',
    'Bugio',
  ),
  Animal(
    'MICO-LEÃO-DOURADO',
    'Grandes Primatas Brasileiros',
    'assets/animals_images/mico_leao_dourado.jpg',
    'O Mico-Leão-Dourado, é um dos primatas mais icônicos do Brasil, conhecido por sua pelagem vibrante e status de conservação crítico.',
    'Leontopithecus Rosalia',
    'Em perigo',
    '20cm a 33cm (Corpo)',
    'sounds/som_mico_leao_dourado.mp3',
    'Mico-le%C3%A3o-dourado',
  ),
  Animal(
    'MICO-LEÃO DE CARA DOURADA',
    'Grandes Primatas Brasileiros',
    'assets/animals_images/mico_leao_cara_dourada.png',
    'O Mico-Leão de Cara Dourada, é um dos micos-leões mais coloridos e ameaçados da Mata Atlântica!',
    'Leontopithecus Chrysomelas',
    'Em Perigo',
    '20cm a 34cm (Corpo)',
    'sounds/som_mico_leao_cara_dourada.mp3',
    'Mico-le%C3%A3o-de-cara-dourada',
  ),
  Animal(
    'PAPAGAIO-CAMPEIRO',
    'Grandes Psitacídeos',
    'assets/animals_images/papagaio_campeiro.jpg',
    'Papagaio-Campeiro, o falante das savanas brasileiras, com seu topete amarelo e personalidade vibrante! Imita sons humanos com clareza (assobios, palavras e até latidos!). Aprende 50+ palavras em cativeiro (com contexto social).',
    'Amazona Ochrocephala',
    'Quase Ameaçado',
    '35cm e 38cm (Corpo)',
    'sounds/som_papagaio_campeiro.mp3',
    'Papagaio-campeiro',
  ),
  Animal(
    'GROU-COROADO',
    'Grou-Coroado',
    'assets/animals_images/grou_coroado.jpg',
    'Grou-Coroado, o bailarino real das savanas africanas, com sua coroa dourada e passos elegantes! Saltos altos, bater de asas e "cantos" trombeteados para atrair parceiros. Casais duradouros (fazem turnê de dança juntos por anos).',
    'Balearica Regulorum',
    'Em Perigo',
    '1m e 1,2m (Corpo)',
    'sounds/som_grou_coroado.mp3',
    'Grou-coroado-cinzento',
  ),
  Animal(
    'Irara',
    'Irara',
    'assets/animals_images/Irara.jpg',
    'Irara, o ágil "furão da selva" das florestas tropicais, um carnívoro misterioso! Escaladora ágil (sobe em árvores como um esquilo). Solta um odor forte (gândulas anais, como um gambá).',
    'Eira Barbara',
    'Pouco Preocupante',
    '60cm e 75cm (Corpo)',
    'sounds/som_irara.mp3',
    'Irara',
  ),
  Animal(
    'Lobo-Guará',
    'Lobo-Guará',
    'assets/animals_images/Lobo.jpg',
    'Lobo-Guará, o elegante "fantasma dos cerrados", o maior canídeo da América do Sul! Urina com cheiro de "maconha" (devido a compostos da lobeira, sua fruta favorita).',
    'Chrysocyon Brachyurus',
    'Quase Ameaçado',
    '1,2m e 1,3m (Corpo)',
    'sounds/som_lobo.mp3',
    'Lobo-guará',
  ),
  Animal(
    'OURIÇO-CACHEIRO',
    'Ouriço',
    'assets/animals_images/ourico.jpg',
    ' Ouriço-Cacheiro, o tímido “guardião espinhoso das árvores”, um roedor arborícola que parece pelúcia…  com espinhos! Durante o dia, dorme enrolado em galhos ou ocos de árvores. Lento no chão, ágil nas árvores.',
    'Coendou Spp',
    'Pouco Preocupante',
    '30cm e 60cm (Corpo)',
    'sounds/som_ourico.mp3',
    'Ouricuri',
  ),
  Animal(
    'Gralha',
    'Pequenas Aves',
    'assets/animals_images/Gralha.jpg',
    'Gralha, a inteligente "rainha das florestas brasileiras", conhecida por sua astúcia e memória afiada! Esconde alimentos (lembra de 90% deles). Reconhece humanos individualmente.',
    'Cyanocorax Yucatanicus',
    'Quase Ameaçada',
    '30cm e 40cm (Corpo)',
    'sounds/som_gralha.mp3',
    'Gralha',
  ),
  Animal(
    'MACACO-PREGO',
    'Pequenos Primatas Brasileiros',
    'assets/animals_images/macaco_prego.jpg',
    'O Macaco-Prego, é um dos primatas mais inteligentes e adaptáveis da América! São capazes de aprendizado social e até de reconhecer quantidade numérica em experimentos!',
    'Sapajus Apella',
    'Pouco Preocupante',
    '30cm a 50cm (Corpo)',
    'sounds/som_macaco_prego.mp3',
    'Macaco-prego',
  ),
  Animal(
    'JANDAIA-VERDADEIRA',
    'Pequenos Psitacídeos',
    'assets/animals_images/jandaia_verdadeira.jpg',
    'A Jandaia-Verdadeira é um dos psitacídeos mais vibrantes e carismáticos do Brasil! Capaz de imitar sons humanos e usar o bico para escalar galhos como um terceiro pé.',
    'Aratinga Jandaya',
    'Quase Ameaçada',
    '30cm (Corpo)',
    'sounds/som_jandaia_verdadeira.mp3',
    'Jandaia-verdadeira',
  ),
  Animal(
    'BABUÍNO-SAGRADO',
    'Primatas Africanos',
    'assets/animals_images/babuino_sagrado.jpg',
    'Babuíno-Sagrado, o primata icônico do Antigo Egito, associado ao deus Thoth! Vivem em sociedades hierárquicas complexas chamadas "sistemas de harém", um macho dominante lidera várias fêmeas e jovens.',
    'Papio Hamadryas',
    'Pouco Preocupante',
    '70cm e 95cm (Corpo)',
    'sounds/som_babuino_sagrado.mp3',
    'Babu%C3%ADno-sagrado',
  ),
  Animal(
    'Tucano',
    'Ramphastídeos',
    'assets/animals_images/Tucano.jpg',
    'Tucano, o "bico-colorido" das florestas tropicais, um dos pássaros mais icônicos do Brasil! Com seu bico, regula temperatura (vasos sanguíneos). Se comunica com crocitos graves e batidas de bico em galhos.',
    'Ramphastos Toco',
    'Pouco Preocupante',
    '50cm e 65cm (Com o bico)',
    'sounds/som_tucano.mp3',
    'Tucano',
  ),
  Animal(
    'Jiboia',
    'Répteis',
    'assets/animals_images/jiboia_AlineCorrea_2025.jpg',
    'Jiboia, a majestosa constritora das florestas tropicais. Constritora (enrola-se em presas e as sufoca antes de engoli-los inteiros). Podem levar semanas para digerir uma refeição grande.',
    'Boa Constrictor',
    'Pouco Preocupante',
    '2m e 3m (Corpo)',
    'sounds/som_jiboia.mp3',
    'Boidae',
  ),
  Animal(
    'Canguru',
    'Canguru',
    'assets/animals_images/Canguru.jpg',
    'Canguru, o símbolo da Áustralia e o maior marsupial do planeta! Machos brigam como boxeadores (usam patas dianteiras e chutes). Quando dominante, ficam vermelho (hormônios intensificam a cor da pele).',
    'Macropus Rufus',
    'Pouco Preocupante',
    '1,8m e 2m (Corpo e Cauda)',
    'sounds/som_canguru.mp3',
    'Canguru',
  ),
  Animal(
    'CERVO-DAMA',
    'Cervídeos',
    'assets/animals_images/cervo_dama.jpg',
    'Cervo-Dama, o elegante "príncipe dos bosques" com chifres em forma de pá e pelagem pintada! Machos emitem roncos profundos e marcam território com urina. (Fêmea na foto acima).',
    'Dama Dama',
    'Pouco Preocupante',
    '1,4m e 1,8m (Corpo)',
    'sounds/som_cervo_dama.mp3',
    'Dama_dama',
  ),
  Animal(
    'SUINDARA',
    'Corujas',
    'assets/animals_images/suindara.jpg',
    'Suindara, a coruja branca mais famosa do Brasil, a "Senhora da Noite" de olhos negros! Grito agudo "shriiiik" (inspirou filmes de terror). Ouve o coração de um rato a 15 m de distância. Gira a cabeça 270° (não tem artérias que bloqueiem o movimento).',
    'Tyto Furcata',
    'Pouco Preocupante',
    '30cm e 40cm (Corpo)',
    'sounds/som_suindara.mp3',
    'Coruja-das-torres',
  ),
  Animal(
    'TAMANDUÁ-MIRIM',
    'Tamanduá',
    'assets/animals_images/tamandua_mirim.jpg',
    'Tamanduá-Mirim, o caçador de formigas ágil e carismático das florestas brasileiras! Noturno e solitário, se defende abraçando o agressor e aplicando golpes com as garras dianteiras.',
    'Tamandua Tetradactyla',
    'Pouco Preocupante',
    '50cm e 88cm (Corpo)',
    'sounds/som_tamandua_mirim.mp3',
    'Tamandu%C3%A1-mirim',
  ),
];